name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hlint:
    name: Haskell HLint - Linux
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v2

    - name: 'Run HLint'
      uses: haskell/actions/hlint-run@v2
      with:
        path: src/
        fail-on: error

# Commented due to complete dependency install and build of cabal
  # build:
  #   name: Haskell-CI - Linux
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup haskell
  #       uses: haskell/actions/setup@v2
  #       with:
  #         ghc-version: '8.10.7' 
  #         cabal-version: 'latest'
  #         enable-stack: true
  #         stack-version: 'latest'

  #     - name: Cache
  #       uses: actions/cache@v3
  #       with:
  #         key: ${{ runner.os }}-${{ github.sha }}
  #         path: ~/.cabal/store
  #         restore-keys: ${{ runner.os }}-${{ github.sha }}

  #     - name: Install freeglut 
  #       run: sudo apt-get install freeglut3 freeglut3-dev

  #     - name: Cabal Update package list
  #       run: cabal update

  #     - name: Cabal Install dependencies
  #       run: cabal install

  #     - name: Cabal Build
  #       run: cabal build
     